const MESSAGE_LENGTH_MIN = 1
const MESSAGE_LENGTH_MAX = 256

const PHONE_NUMBER_MIN = 1111
const PHONE_NUMBER_MAX = 999999999999

const ID_LENGTH = 24

exports.MESSAGE_LENGTH_MIN = MESSAGE_LENGTH_MIN
exports.MESSAGE_LENGTH_MAX = MESSAGE_LENGTH_MAX
exports.PHONE_NUMBER_MIN = PHONE_NUMBER_MIN
exports.PHONE_NUMBER_MAX = PHONE_NUMBER_MAX
exports.ID_LENGTH = ID_LENGTH
